# Generated by Django 4.2.9 on 2024-03-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_basket_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='basket_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='store.basket'),
        ),
    ]
